export const actionTypes = {
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAIL: "REGISTER_FAIL",
	LOGOUT: "LOGOUT",
	CHANGEPASS_SUCCESS: "CHANGEPASS_SUCCESS",
	CHANGEPASS_FAIL: "CHANGEPASS_FAIL",
};
