export const actionTypes = {
	LOGIN_SUCCESS: "LOGIN_SUCCESS",
	LOGIN_FAIL: "LOGIN_FAIL",
	REGISTER_SUCCESS: "REGISTER_SUCCESS",
	REGISTER_FAIL: "REGISTER_FAIL",
	LOGOUT: "LOGOUT",
	CHANGEPASS_SUCCESS: "CHANGEPASS_SUCCESS",
	CHANGEPASS_FAIL: "CHANGEPASS_FAIL",
	UPLOAD_AVATAR_SUCCESS: "UPLOAD_AVATAR_SUCCESS",
	UPLOAD_AVATAR_FAIL: "UPLOAD_AVATAR_FAIL",
	UPDATE_USERINFO_SUCCESS: "UPDATE_USERINFO_SUCCESS",
	UPDATE_USERINFO_FAIL: "UPDATE_USERINFO_FAIL",
	TRIGGER_NOTIFICATION: "TRIGGER_NOTIFICATION",
};
